# Generated by Django 3.1.5 on 2021-05-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('father', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=11)),
                ('intro', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
